#!/bin/sh /etc/rc.common
# Tproxy rules for OpenWrt

START=97
STOP=15
USE_PROCD=1

GATEWAY="192.168.2.1"

wait_for_gateway() {
    until ping -c1 $GATEWAY >/dev/null 2>&1; do
        sleep 1
    done
}

start_service() {
    echo "Waiting for gateway $GATEWAY..."
    wait_for_gateway
    echo "Applying TProxy rules..."

    ip rule add fwmark 1 table 100
    ip route add local 0.0.0.0/0 dev lo table 100
    ip route add default via $GATEWAY
    nft -f /root/nftables.rulesv46
}

stop_service() {
    echo "Removing TProxy rules..."

    ip rule del fwmark 1 table 100
    ip route del local 0.0.0.0/0 dev lo table 100
    ip route del default via $GATEWAY
    nft flush ruleset
}